spring.application.name=estate
server.port=8081

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://quyethv2003:Quyetdepchy%409@mongoturtorial.oaop2a9.mongodb.net/real_estate_db?retryWrites=true&w=majority
spring.data.mongodb.database=real_estate_db

